# Generated by Django 4.1.7 on 2023-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(default=1, upload_to='resume'),
            preserve_default=False,
        ),
    ]
