# Generated by Django 4.1.7 on 2023-02-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_resume_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='phone_number',
        ),
    ]
