# Generated by Django 4.1.7 on 2023-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_resume_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
