# Generated by Django 4.1.7 on 2023-02-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_client",
                    models.CharField(max_length=255, verbose_name="Имя клиента"),
                ),
                (
                    "financing_agency",
                    models.CharField(
                        max_length=255, verbose_name="Финансовое агентство"
                    ),
                ),
                ("country", models.CharField(max_length=255, verbose_name="Страна")),
                ("sector", models.CharField(max_length=255, verbose_name="Сектор")),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=255,
                        verbose_name="Месяц",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Год")),
                (
                    "projects_detail",
                    models.TextField(max_length=255, verbose_name="Детали проекта"),
                ),
            ],
        ),
    ]
