# Generated by Django 4.1.4 on 2023-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Non-governmental', 'Non-governmental'), ('Local governance', 'Local governance')], max_length=255, verbose_name='Сектор'),
        ),
    ]
