# Generated by Django 4.1.4 on 2023-02-21 08:02

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projects_detail',
            field=django_quill.fields.QuillField(),
        ),
    ]
