# Generated by Django 4.1.7 on 2023-02-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0003_alter_project_projects_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.ourclients', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
