# Generated by Django 4.1.7 on 2023-02-27 10:32

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_ourclients_сompany_name'),
        ('projects', '0004_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.ourclients', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.ourclients', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='country_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='project',
            name='country_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='project',
            name='financing_agency_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Финансовое агентство'),
        ),
        migrations.AddField(
            model_name='project',
            name='financing_agency_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Финансовое агентство'),
        ),
        migrations.AddField(
            model_name='project',
            name='month_en',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='project',
            name='month_ru',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_of_client_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_of_client_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='project',
            name='projects_detail_en',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projects_detail_ru',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sector_en',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Non-governmental', 'Non-governmental'), ('Local governance', 'Local governance')], max_length=255, null=True, verbose_name='Сектор'),
        ),
        migrations.AddField(
            model_name='project',
            name='sector_ru',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Non-governmental', 'Non-governmental'), ('Local governance', 'Local governance')], max_length=255, null=True, verbose_name='Сектор'),
        ),
        migrations.AddField(
            model_name='project',
            name='year_en',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='project',
            name='year_ru',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
    ]
