# Generated by Django 4.1.7 on 2023-02-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_client_en_project_client_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year_ru',
        ),
    ]
