# Generated by Django 4.1.7 on 2023-02-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_client_en_remove_project_client_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='month',
            field=models.CharField(max_length=255, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='project',
            name='month_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='project',
            name='month_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Месяц'),
        ),
    ]
