# Generated by Django 4.1.7 on 2023-03-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_month_alter_project_month_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clients_logo',
            field=models.ImageField(default=1, upload_to='clients_logo', verbose_name='Логотип клиента'),
            preserve_default=False,
        ),
    ]
