<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-02 12:16
=======
# Generated by Django 4.1.7 on 2023-04-02 13:08
>>>>>>> 7543f4ea5644bccb6d7bbdd83a4b143a637f80a8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('clients', '0004_partnerimage'),
=======
        ('clients', '0005_alter_ourclients_category_alter_ourclients_image'),
>>>>>>> 7543f4ea5644bccb6d7bbdd83a4b143a637f80a8
        ('projects', '0008_project_clients_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.ourclients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clients_logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients_logo', verbose_name='Логотип клиента'),
        ),
    ]
