# Generated by Django 4.1.7 on 2023-04-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_partnerimage'),
        ('projects', '0009_alter_project_client_alter_project_clients_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.ourclients', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='clients_logo',
            field=models.ImageField(default=1, upload_to='clients_logo', verbose_name='Логотип клиента'),
            preserve_default=False,
        ),
    ]
