# Generated by Django 4.1.7 on 2023-04-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_partnerimage'),
        ('projects', '0010_alter_project_client_alter_project_clients_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.ourclients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clients_logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients_logo', verbose_name='Логотип клиента'),
        ),
    ]
