# Generated by Django 4.1.7 on 2023-02-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(default=1, upload_to='news/main_image', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
