# Generated by Django 4.1.7 on 2023-02-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Опубликовано в:"
            ),
        ),
    ]
