# Generated by Django 4.1.4 on 2023-02-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newimages',
            old_name='new',
            new_name='news',
        ),
    ]
