# Generated by Django 4.1.4 on 2023-02-21 13:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_new_newimages_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
