# Generated by Django 4.1.7 on 2023-02-27 19:37

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=775, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=775, null=True, verbose_name='Заголовок'),
        ),
    ]
