# Generated by Django 4.1.7 on 2023-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_content_en_news_content_ru_news_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/main_image', verbose_name='Изображение'),
        ),
    ]
