# Generated by Django 4.1.7 on 2023-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(verbose_name='Опубликовано в:'),
        ),
    ]
