# Generated by Django 4.1.4 on 2023-02-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(verbose_name='Добавлено в')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denotation', models.CharField(max_length=255, verbose_name='Услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_services.services')),
            ],
        ),
    ]
