# Generated by Django 4.1.4 on 2023-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в'),
        ),
    ]
