# Generated by Django 4.1.4 on 2023-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0002_alter_services_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Изображение'),
        ),
    ]
