# Generated by Django 4.1.4 on 2023-02-21 13:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0003_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
