# Generated by Django 4.1.7 on 2023-02-27 19:37

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('our_services', '0004_alter_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_ru',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='servicesinclude',
            name='denotation_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='servicesinclude',
            name='denotation_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default=1, upload_to='services', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
