# Generated by Django 4.1.7 on 2023-04-02 19:38

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_quill.fields.QuillField(verbose_name='Описание')),
                ('description_en', django_quill.fields.QuillField(null=True, verbose_name='Описание')),
                ('description_ru', django_quill.fields.QuillField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='associated_aca_memebers', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='EcasRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled')),
                ('title_en', django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled')),
                ('title_ru', django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associated_aca_memebers.members')),
            ],
        ),
    ]
