# Generated by Django 4.1.7 on 2023-02-24 18:37

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', django_quill.fields.QuillField()),
                ('image', models.ImageField(upload_to='associated_aca_memebers')),
                ('ecas_role', django_quill.fields.QuillField()),
            ],
        ),
    ]
