# Generated by Django 4.1.7 on 2023-02-24 19:14

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('associated_aca_memebers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='discription',
            field=django_quill.fields.QuillField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='members',
            name='ecas_role',
            field=django_quill.fields.QuillField(verbose_name='As eca expert was envoled'),
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(upload_to='associated_aca_memebers', verbose_name='Изображение'),
        ),
    ]
