# Generated by Django 4.1.7 on 2023-04-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associated_aca_memebers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecasrole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecas_roles', to='associated_aca_memebers.members'),
        ),
    ]
