# Generated by Django 4.1.7 on 2023-02-27 19:37

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('associated_aca_memebers', '0002_alter_members_discription_alter_members_ecas_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='discription_en',
            field=django_quill.fields.QuillField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='members',
            name='discription_ru',
            field=django_quill.fields.QuillField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='members',
            name='ecas_role_en',
            field=django_quill.fields.QuillField(null=True, verbose_name='As eca expert was envoled'),
        ),
        migrations.AddField(
            model_name='members',
            name='ecas_role_ru',
            field=django_quill.fields.QuillField(null=True, verbose_name='As eca expert was envoled'),
        ),
    ]
