# Generated by Django 4.1.7 on 2023-03-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associated_aca_memebers', '0003_members_discription_en_members_discription_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='discription_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='discription_ru',
            new_name='description_ru',
        ),
    ]
