# Generated by Django 4.1.7 on 2023-04-02 13:08

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('associated_aca_memebers', '0004_rename_discription_members_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='ecas_role',
        ),
        migrations.RemoveField(
            model_name='members',
            name='ecas_role_en',
        ),
        migrations.RemoveField(
            model_name='members',
            name='ecas_role_ru',
        ),
        migrations.CreateModel(
            name='EcasRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled')),
                ('title_en', django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled')),
                ('title_ru', django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associated_aca_memebers.members')),
            ],
        ),
    ]
