# Generated by Django 4.1.7 on 2023-04-02 12:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('associated_aca_memebers', '0004_rename_discription_members_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='ecas_role',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled'),
        ),
        migrations.AlterField(
            model_name='members',
            name='ecas_role_en',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled'),
        ),
        migrations.AlterField(
            model_name='members',
            name='ecas_role_ru',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='As eca expert was envoled'),
        ),
    ]
