# Generated by Django 4.1.7 on 2023-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourclients',
            name='сompany_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название компании'),
            preserve_default=False,
        ),
    ]
