# Generated by Django 4.1.7 on 2023-02-27 19:37

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_ourclients_сompany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='content_en',
            field=django_quill.fields.QuillField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='content_ru',
            field=django_quill.fields.QuillField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='сompany_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='ourclients',
            name='сompany_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название компании'),
        ),
    ]
