# Generated by Django 4.1.7 on 2023-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_category_title_en_category_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Компания')),
                ('image', models.ImageField(upload_to='clients', verbose_name='Изображение')),
            ],
        ),
    ]
