# Generated by Django 4.1.7 on 2023-04-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_partnerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourclients',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ourclients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients', verbose_name='Изображение'),
        ),
    ]
